//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonus()
        {
            this.Kaart_Bonussen = new HashSet<Kaart_Bonus>();
        }
    
        public int Id { get; set; }
        public string Niet_Bruikbaar_Door { get; set; }
        public string Bruikbaar_Door { get; set; }
        public int Waarde { get; set; }
        public string Waarop_Effect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaart_Bonus> Kaart_Bonussen { get; set; }
    }
}
