//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaarten_Stapel
    {
        public int Id { get; set; }
        public int Kaart_Id { get; set; }
        public int Stapel_Id { get; set; }
    
        public virtual Kaart Kaart { get; set; }
        public virtual Stapel Stapel { get; set; }
    }
}
