//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kaart()
        {
            this.Kaart_Bonussen = new HashSet<Kaart_Bonus>();
            this.Kaarten_Stapels = new HashSet<Kaarten_Stapel>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Beschrijving { get; set; }
        public string Afbeelding { get; set; }
        public int Type_id { get; set; }
        public Nullable<bool> Eenmalig { get; set; }
        public string Wanneer_Bruikbaar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaart_Bonus> Kaart_Bonussen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaarten_Stapel> Kaarten_Stapels { get; set; }
        public virtual Kerkerkaart Kerkerkaart { get; set; }
        public virtual Schatkaart Schatkaart { get; set; }
        public virtual Type Type { get; set; }
    }
}
