//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kerkerkaart
    {
        public int Id { get; set; }
        public string Beschrijving_2 { get; set; }
        public string Portie_Ellende { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Aantal_schatten { get; set; }
        public Nullable<bool> Ondood { get; set; }
        public Nullable<int> Aantal_Levels { get; set; }
        public Nullable<int> Tijdelijke_Bonus { get; set; }
    
        public virtual Kaart Kaart { get; set; }
    }
}
