//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MunchkinEntities : DbContext
    {
        public MunchkinEntities()
            : base("name=MunchkinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonus> Bonussen { get; set; }
        public virtual DbSet<Kaart_Bonus> Kaart_Bonussen { get; set; }
        public virtual DbSet<Kaart> Kaarten { get; set; }
        public virtual DbSet<Kaarten_Stapel> Kaarten_Stapels { get; set; }
        public virtual DbSet<Kerkerkaart> Kerkerkaarten { get; set; }
        public virtual DbSet<Schatkaart> Schatkaarten { get; set; }
        public virtual DbSet<Speler> Spelers { get; set; }
        public virtual DbSet<Stapel> Stapels { get; set; }
        public virtual DbSet<Toernooi> Toernooien { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Wedstrijd_Speler> Wedstrijd_Spelers { get; set; }
        public virtual DbSet<Wedstrijd> Wedstrijden { get; set; }
    }
}
