//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stapel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stapel()
        {
            this.Kaarten_Stapels = new HashSet<Kaarten_Stapel>();
            this.Wedstrijd_Speler_Handkaarten = new HashSet<Wedstrijd_Speler>();
            this.Wedstrijd_Kerkerkaarten_Aflegstapel = new HashSet<Wedstrijd>();
            this.Wedstrijd_Kerkerkaarten_Trekstapel = new HashSet<Wedstrijd>();
            this.Wedstrijd_Schatkaarten_Aflegstapel = new HashSet<Wedstrijd>();
            this.Wedstrijd_Schatkaarten_Trekstapel = new HashSet<Wedstrijd>();
            this.Wedstrijd_Speler_Veldkaarten = new HashSet<Wedstrijd_Speler>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaarten_Stapel> Kaarten_Stapels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd_Speler> Wedstrijd_Speler_Handkaarten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd> Wedstrijd_Kerkerkaarten_Aflegstapel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd> Wedstrijd_Kerkerkaarten_Trekstapel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd> Wedstrijd_Schatkaarten_Aflegstapel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd> Wedstrijd_Schatkaarten_Trekstapel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd_Speler> Wedstrijd_Speler_Veldkaarten { get; set; }
    }
}
