//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toernooi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toernooi()
        {
            this.Wedstrijden = new HashSet<Wedstrijd>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int Winnaar_Id { get; set; }
    
        public virtual Speler Speler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd> Wedstrijden { get; set; }
    }
}
