//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijd_Speler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wedstrijd_Speler()
        {
            this.Level = 1;
            this.Ras = "Mens";
            this.Vluchtbonus = 0;
            this.Gevechtsbonus = 0;
            this.Tijdelijke_Bonus = 0;
        }
    
        public int Id { get; set; }
        public int Speler_Id { get; set; }
        public Nullable<int> Wedstrijd_Id { get; set; }
        public int Handkaarten_Id { get; set; }
        public int Veldkaarten_Id { get; set; }
        public Nullable<int> Level { get; set; }
        public string Ras { get; set; }
        public Nullable<int> Vluchtbonus { get; set; }
        public Nullable<int> Gevechtsbonus { get; set; }
        public Nullable<int> Tijdelijke_Bonus { get; set; }
    
        public virtual Speler Speler { get; set; }
        public virtual Stapel Stapel_Handkaarten { get; set; }
        public virtual Stapel Stapel_Veldkaarten { get; set; }
        public virtual Wedstrijd Wedstrijd { get; set; }
    }
}
