//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijd_Speler
    {
        public int Id { get; set; }
        public int Speler_Id { get; set; }
        public int Wedstrijd_Id { get; set; }
        public int Handkaarten_Id { get; set; }
        public int Veldkaarten_Id { get; set; }
    
        public virtual Speler Speler { get; set; }
        public virtual Stapel Stapel_Handkaarten { get; set; }
        public virtual Stapel Stapel_Veldkaarten { get; set; }
        public virtual Wedstrijd Wedstrijd { get; set; }
    }
}
