//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munckin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wedstrijd()
        {
            this.Wedstrijd_Spelers = new HashSet<Wedstrijd_Speler>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Winnaar_Id { get; set; }
        public Nullable<int> Toernooi_Id { get; set; }
        public int Kerkerkaarten_Trekstapel_Id { get; set; }
        public int Kerkerkaarten_Aflegstapel_Id { get; set; }
        public int Schatkaarten_Trekstapel_Id { get; set; }
        public int Schatkaarten_Aflegstapel_Id { get; set; }
    
        public virtual Speler Speler { get; set; }
        public virtual Stapel Kerkerkaarten_Aflegstapel { get; set; }
        public virtual Stapel Kerkerkaarten_Trekstapel { get; set; }
        public virtual Stapel Schatkaarten_Aflegstapel { get; set; }
        public virtual Stapel Schatkaarten_Trekstapel { get; set; }
        public virtual Toernooi Toernooi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijd_Speler> Wedstrijd_Spelers { get; set; }
    }
}
